---
# tasks file for kubernetes

#-------------------------DISABLE SWAP-------------------------------#
- name: Disable swaap
  become: true
  ansible.builtin.shell: swapoff -a
- name: disable SWAP in fstab (Kubeadm requirement) 
  become: true
  ansible.builtin.replace:
   path: /etc/fstab
   regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
   replace: '# \1'

#-------------------------k8s Install-------------------------------#
- name: Add Kubernetes apt-key
  become: true
  ansible.builtin.get_url:
   url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
   dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
   mode: '0644'
   force: true
- name: Add Kubernetes' APT repository
  become: true
  ansible.builtin.apt_repository:
   repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
   state: present
   update_cache: yes
- name: install Kubeadm, Kubectl, Kubelet
  become: true
  ansible.builtin.apt:
   package:
    - kubeadm
    - kubelet
    - kubectl
   update_cache: true

- name: Remove containerd config
  become: true
  ansible.builtin.file:
   path: /etc/containerd/config.toml
   state: absent

- name: enable the Containerd service and start it
  become: true
  ansible.builtin.systemd:
   name: containerd
   state: restarted
   enabled: true
   daemon-reload: true