#--------------------master node----------------------------------------------#
- hosts: master
  become: yes
  tasks:
    - name: get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - name: Store join command
      become: false
      local_action: copy content="{{ join_command }}" dest="/home/kali/kubeadm-join.command"
    - name: Debug
      debug: msg={{join_command}}

#------------------------------worker Node Section----------------------------#
- hosts: worker
  become: yes
  tasks:
   - name: Copy join command from Ansible host to the worker nodes.
     become: yes
     ansible.builtin.copy:
       src: /home/kali/kubeadm-join.command
       dest: /etc/kubernetes/kubeadm-join.command
       mode: 0777
   - name: Join the Worker nodes to the cluster.
     become: yes
     ansible.builtin.command: sh /etc/kubernetes/kubeadm-join.command