---
- name: Backup Configure
  hosts: cisco
  connection: network_cli
  tasks:
   - name: Backup running config
     cisco.ios.ios_config:
      backup: true
      backup_options:
        dir_path:
     register: backup