---
- name: Telnet to cisco device
  hosts: cisco
  connection: network_cli

  tasks:
    - name: Telnet to setup ssh
      ansible.netcommon.telnet:
        user: cisco
        password: cisco
        login_prompt: "Username:"
        prompts:
          - "[#>]"
        command:
          - configure terminal
          - ssh version 2
          - commit
        register: output